# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

AdminUser.create([
  { :email => "tataihono.nikora@gmail.com", :encrypted_password => "$2a$10$1d0OS9RcaJw2gpbP7HtfDu8EEf1Wzw/vmprHWrmRvv0d4f4iJScoS", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2013-08-22 04:27:31", :updated_at => "2013-08-22 04:27:31" }
], :without_protection => true )



Answer.create([
  { :content_id => nil, :person_id => nil, :data => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Content.create([
  { :content_type => 1, :foreign_id => 9829, :name => "Place", :created_at => "2013-08-22 00:32:24", :updated_at => "2013-08-22 00:32:24" },
  { :content_type => 7, :foreign_id => 9831, :name => "Magazine", :created_at => "2013-08-22 00:33:02", :updated_at => "2013-08-22 00:33:02" },
  { :content_type => 4, :foreign_id => 9834, :name => "Interest", :created_at => "2013-08-22 00:33:56", :updated_at => "2013-08-22 00:33:56" },
  { :content_type => 4, :foreign_id => 9835, :name => "Kennedy", :created_at => "2013-08-22 00:34:27", :updated_at => "2013-08-22 00:34:27" },
  { :content_type => 1, :foreign_id => 9836, :name => "University", :created_at => "2013-08-22 00:34:48", :updated_at => "2013-08-22 00:34:48" },
  { :content_type => 1, :foreign_id => 9837, :name => "Faculty", :created_at => "2013-08-22 00:36:35", :updated_at => "2013-08-22 00:36:35" },
  { :content_type => 4, :foreign_id => 9838, :name => "Year", :created_at => "2013-08-22 00:36:56", :updated_at => "2013-08-22 00:36:56" },
  { :content_type => 4, :foreign_id => 9839, :name => "Outreach", :created_at => "2013-08-22 00:37:24", :updated_at => "2013-08-22 00:37:24" },
  { :content_type => 4, :foreign_id => 9840, :name => "Locale", :created_at => "2013-08-22 00:37:50", :updated_at => "2013-08-22 00:37:50" },
  { :content_type => 7, :foreign_id => 9833, :name => "Journey", :created_at => "2013-08-22 00:33:26", :updated_at => "2013-08-22 01:26:10" }
], :without_protection => true )



Outreach.create([
  { :url => "localhost", :mhubid => 7936, :created_at => "2013-08-19 01:57:25", :updated_at => "2013-08-22 04:23:12", :dial_code => "+64", :sms => "Hey! OTG SL.", :org_name => "Student Life", :prize_message => "with a chance to win a $250 voucher to fly anywhere!", :logo_file_name => "logo-f18f531b0fe58ea11823141a649c0dfb.png", :logo_content_type => "image/png", :logo_file_size => 16630, :logo_updated_at => "2013-08-22 04:19:17", :prize_message_long => "Complete this survey and get on the journey with a chance to win 5000p of free flights" }
], :without_protection => true )



Person.create([
  { :first_name => nil, :last_name => nil, :mobile => nil, :email => nil, :gender => nil, :foreign_id => nil, :created_at => nil, :updated_at => nil, :outreach => nil }
], :without_protection => true )


